import React, { useMemo, useState } from 'react';
import { Eye, MessageCircle, Plus, Search, Trash2 } from 'lucide-react';
import { Orcamento, StatusOrcamento } from '../types';
import { formatarData, formatarMoeda, formatarTelefoneVisual, obterRotuloStatus } from '../utils/format';

interface Props { orcamentos: Orcamento[]; onAbrirNovo: () => void; onVerDetalhes: (o: Orcamento) => void; onAtualizarStatus: (id: string, status: StatusOrcamento) => void; onExcluir: (id: string) => void; termoBuscaGlobal?: string; }

export const OrcamentosView: React.FC<Props> = ({ orcamentos, onAbrirNovo, onVerDetalhes, onAtualizarStatus, onExcluir, termoBuscaGlobal = '' }) => {
  const [busca, setBusca] = useState(termoBuscaGlobal);
  const [filtro, setFiltro] = useState<'todos' | StatusOrcamento>('todos');
  const [ordenacao, setOrdenacao] = useState<'recente' | 'maior' | 'menor'>('recente');

  const lista = useMemo(() => orcamentos.filter(o => {
    const q = busca.toLowerCase().trim();
    const match = !q || [o.cliente, o.servico, o.descricao || '', o.whatsapp, o.numero].some(v => v.toLowerCase().includes(q));
    return match && (filtro === 'todos' || o.status === filtro);
  }).sort((a, b) => ordenacao === 'maior' ? b.total - a.total : ordenacao === 'menor' ? a.total - b.total : new Date(b.criadoEm).getTime() - new Date(a.criadoEm).getTime()), [orcamentos, busca, filtro, ordenacao]);

  return <div className="fz-page space-y-5">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-xs font-black uppercase tracking-[.16em] text-emerald-600">Orçamentos</span><h1 className="mt-1 text-3xl font-black tracking-tight">Seus orçamentos</h1><p className="mt-1 text-sm text-slate-500">Acompanhe todas as suas oportunidades.</p></div><button onClick={onAbrirNovo} className="flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white hover:bg-emerald-700"><Plus className="h-4 w-4" /> Novo orçamento</button></div>

    <div className="space-y-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={busca} onChange={e => setBusca(e.target.value)} placeholder="Buscar cliente, serviço, telefone..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100" /></div><select value={ordenacao} onChange={e => setOrdenacao(e.target.value as typeof ordenacao)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-medium outline-none"><option value="recente">Mais recentes</option><option value="maior">Maior valor</option><option value="menor">Menor valor</option></select></div><div className="flex gap-2 overflow-x-auto pb-1">{(['todos','aguardando','aceito','recusado','concluido'] as const).map(s => <button key={s} onClick={() => setFiltro(s)} className={`whitespace-nowrap rounded-xl px-3 py-1.5 text-xs font-bold ${filtro === s ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-600'}`}>{s === 'todos' ? `Todos (${orcamentos.length})` : `${obterRotuloStatus(s)} (${orcamentos.filter(o => o.status === s).length})`}</button>)}</div></div>

    {lista.length === 0 ? <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center shadow-sm"><p className="font-semibold text-slate-600">Nenhum orçamento encontrado.</p><button onClick={() => { setBusca(''); setFiltro('todos'); }} className="mt-2 text-xs font-bold text-emerald-600">Limpar filtros</button></div> : <div className="space-y-3">{lista.map(o => <div key={o.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><button onClick={() => onVerDetalhes(o)} className="truncate text-left font-bold hover:text-emerald-600">{o.servico}</button><select value={o.status} onChange={e => onAtualizarStatus(o.id, e.target.value as StatusOrcamento)} className={`rounded-full border-0 px-2 py-1 text-[10px] font-black uppercase outline-none ${o.status === 'aceito' || o.status === 'concluido' ? 'bg-emerald-100 text-emerald-800' : o.status === 'recusado' ? 'bg-rose-100 text-rose-800' : 'bg-amber-100 text-amber-800'}`}><option value="aguardando">Aguardando</option><option value="aceito">Aceito</option><option value="recusado">Recusado</option><option value="concluido">Concluído</option></select></div><p className="mt-1 text-xs text-slate-500">{o.numero} · {o.cliente} · {formatarData(o.criadoEm)} {o.whatsapp && `· ${formatarTelefoneVisual(o.whatsapp)}`}</p>{o.descricao && <p className="mt-2 line-clamp-2 text-xs text-slate-500">{o.descricao}</p>}</div><div className="flex items-center justify-between gap-3 lg:justify-end"><div><span className="block text-[10px] font-bold uppercase text-slate-400">Total</span><strong className="text-lg font-black">{formatarMoeda(o.total)}</strong></div><div className="flex gap-1.5">{o.whatsapp && <button onClick={() => onVerDetalhes(o)} title={o.status === 'aguardando' ? 'Enviar lembrete' : 'Enviar WhatsApp'} className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><MessageCircle className="h-4 w-4" /></button>}<button onClick={() => onVerDetalhes(o)} className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><Eye className="h-4 w-4" /></button><button onClick={() => onExcluir(o.id)} className="flex h-9 w-9 items-center justify-center rounded-xl bg-rose-50 text-rose-600"><Trash2 className="h-4 w-4" /></button></div></div></div></div>)}</div>}
  </div>;
};
